name = "Test Pipeline"
version = "0.1.0"

[trigger]
on = "push"

[stages.build]
name = "Build"

[[stages.build.steps]]
name = "Build"
command = "echo 'cargo build'"

[stages.lint]
name = "Lint"

[[stages.lint.steps]]
name = "Clippy"
command = "echo 'cargo clippy'"

[[stages.lint.steps]]
name = "Format"
command = "echo 'cargo fmt'"

[[stages.lint.steps]]
name = "Machete"
command = "echo 'cargo machete'"

[stages.test]
name = "Test"

[[stages.test.steps]]
name = "Test"
command = "echo 'cargo test'"

[[stages.test.steps]]
name = "Coverage"
command = "echo 'cargo test -- --nocapture'"
