config:
  backup: true
  create: true
  dotpath: dotfiles
  impignore:
  - '*/nushell/history.txt'
dotfiles:
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  f_kitty.conf:
    src: config/kitty/kitty.conf
    dst: ~/.config/kitty/kitty.conf
  f_config.toml:
    src: config/typeracer/config.toml
    dst: ~/.config/typeracer/config.toml
  d_nushell:
    src: config/nushell
    dst: ~/.config/nushell
  f_config:
    src: config/warpd/config
    dst: ~/.config/warpd/config
  f_warpd.service:
    src: config/systemd/user/warpd.service
    dst: ~/.config/systemd/user/warpd.service
  f_colemak.service:
    src: config/systemd/user/colemak.service
    dst: ~/.config/systemd/user/colemak.service
  f_colemak-dh-extend-ansi.kbd:
    src: colemak-dh-extend-ansi.kbd
    dst: ~/colemak-dh-extend-ansi.kbd
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  d_ion:
    src: config/ion
    dst: ~/.config/ion
  f_rc.elv:
    src: config/elvish/rc.elv
    dst: ~/.config/elvish/rc.elv
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
  f_nitrogen.cfg:
    src: config/nitrogen/nitrogen.cfg
    dst: ~/.config/nitrogen/nitrogen.cfg
  d_fw:
    src: config/leftwm/themes/fw
    dst: ~/.config/leftwm/themes/fw
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  f_config.ron:
    src: config/leftwm/config.ron
    dst: ~/.config/leftwm/config.ron
profiles:
  default:
    dotfiles:
    - f_starship.toml
    - f_kitty.conf
    - f_config.toml
    - d_nushell
    - f_config
    - f_warpd.service
    - f_colemak.service
    - f_colemak-dh-extend-ansi.kbd
    - f_alacritty.yml
    - d_ion
    - f_rc.elv
    - d_fw
    - d_rofi
    - f_config.ron
  laptop:
    dotfiles:
    - f_xprofile
    - f_nitrogen.cfg
