config:
  backup: true
  create: true
  dotpath: dotfiles
  impignore:
  - '*/nushell/history.txt'
dotfiles:
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  f_kitty.conf:
    src: config/kitty/kitty.conf
    dst: ~/.config/kitty/kitty.conf
  f_config.toml:
    src: config/typeracer/config.toml
    dst: ~/.config/typeracer/config.toml
  d_nushell:
    src: config/nushell
    dst: ~/.config/nushell
  f_config:
    src: config/warpd/config
    dst: ~/.config/warpd/config
  f_warpd.service:
    src: config/systemd/user/warpd.service
    dst: ~/.config/systemd/user/warpd.service
  f_colemak.service:
    src: config/systemd/user/colemak.service
    dst: ~/.config/systemd/user/colemak.service
  f_colemak-dh-extend-ansi.kbd:
    src: colemak-dh-extend-ansi.kbd
    dst: ~/colemak-dh-extend-ansi.kbd
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  d_ion:
    src: config/ion
    dst: ~/.config/ion
  f_rc.elv:
    src: config/elvish/rc.elv
    dst: ~/.config/elvish/rc.elv
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
  f_nitrogen.cfg:
    src: config/nitrogen/nitrogen.cfg
    dst: ~/.config/nitrogen/nitrogen.cfg
  d_fw:
    src: config/leftwm/themes/fw
    dst: ~/.config/leftwm/themes/fw
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  f_config.ron:
    src: config/leftwm/config.ron
    dst: ~/.config/leftwm/config.ron
  f_config.ini:
    src: config/polybar/config.ini
    dst: ~/.config/polybar/config.ini
  f_xmonad.hs:
    src: config/xmonad/xmonad.hs
    dst: ~/.config/xmonad/xmonad.hs
  d_xmobar:
    src: config/xmobar
    dst: ~/.config/xmobar
  f_xmobarrc_2nd:
    src: config/xmobar/xmobarrc_2nd
    dst: ~/.config/xmobar/xmobarrc_2nd
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  d_completions:
    src: config/fish/completions
    dst: ~/.config/fish/completions
  d_conf.d:
    src: config/fish/conf.d
    dst: ~/.config/fish/conf.d
  d_laptop:
    src: Pictures/wallpapers/laptop
    dst: ~/Pictures/wallpapers/laptop
  d_pc:
    src: Pictures/wallpapers/pc
    dst: ~/Pictures/wallpapers/pc
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_tmux:
    src: config/tmux
    dst: ~/.config/tmux
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
profiles:
  default:
    dotfiles:
    - f_starship.toml
    - f_kitty.conf
    - f_config.toml
    - d_nushell
    - f_config
    - f_warpd.service
    - f_alacritty.yml
    - d_ion
    - f_rc.elv
    - d_fw
    - d_rofi
    - f_config.ron
    - f_config.ini
    - f_config.fish
    - d_completions
    - d_conf.d
    - d_tmux
  laptop:
    dotfiles:
    - d_laptop
  pc:
    dotfiles:
    - d_pc
  anywhere:
    dotfiles:
    - d_alacritty
  me-pc:
    dotfiles:
    - d_nvim
