version: '3'

tasks:
  init:
    desc: Initialize chezmoi on a new machine
    cmds:
      - chezmoi init --source={{.TASKFILE_DIR}}/home
  deploy:
    desc: Apply dotfiles to the current machine
    cmds:
      - chezmoi apply
  diff:
    desc: Show pending changes
    cmds:
      - chezmoi diff
