#!/usr/bin/env bash
export $(dbus-launch)
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"
