import = ["/home/anyone/.config/alacritty/dracula.toml"]
shell = "tmux"

[font]
size = 12.0

[font.normal]
family = "CaskaydiaCove Nerd Font"

[window]
opacity = 0.7
blur = true

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 100
lines = 30

