[symlinks]
"config/fish/completions/asdf.fish" = "/home/me/.config/fish/completions/asdf.fish"
"config/fish/completions/atuin.fish" = "/home/me/.config/fish/completions/atuin.fish"
"config/fish/completions/aws.fish" = "/home/me/.config/fish/completions/aws.fish"
"config/fish/completions/dotdrop.fish" = "/home/me/.config/fish/completions/dotdrop.fish"
"config/fish/completions/dotter.fish" = "/home/me/.config/fish/completions/dotter.fish"
"config/fish/completions/ghostty.fish" = "/home/me/.config/fish/completions/ghostty.fish"
"config/fish/completions/helm.fish" = "/home/me/.config/fish/completions/helm.fish"
"config/fish/completions/k3d.fish" = "/home/me/.config/fish/completions/k3d.fish"
"config/fish/completions/kind.fish" = "/home/me/.config/fish/completions/kind.fish"
"config/fish/completions/kustomize.fish" = "/home/me/.config/fish/completions/kustomize.fish"
"config/fish/completions/proto.fish" = "/home/me/.config/fish/completions/proto.fish"
"config/fish/completions/pulumi.fish" = "/home/me/.config/fish/completions/pulumi.fish"
"config/fish/completions/rtx.fish" = "/home/me/.config/fish/completions/rtx.fish"
"config/fish/completions/rust.fish" = "/home/me/.config/fish/completions/rust.fish"
"config/fish/completions/sqlx-rust.fish" = "/home/me/.config/fish/completions/sqlx-rust.fish"
"config/fish/completions/task.fish" = "/home/me/.config/fish/completions/task.fish"
"config/fish/completions/temporal.fish" = "/home/me/.config/fish/completions/temporal.fish"
"config/fish/conf.d/01-envs.fish" = "/home/me/.config/fish/conf.d/01-envs.fish"
"config/fish/conf.d/02-loader-asdf.fish" = "/home/me/.config/fish/conf.d/02-loader-asdf.fish"
"config/fish/conf.d/02-loader-atuin.fish" = "/home/me/.config/fish/conf.d/02-loader-atuin.fish"
"config/fish/conf.d/02-loader-direnv.fish" = "/home/me/.config/fish/conf.d/02-loader-direnv.fish"
"config/fish/conf.d/02-loader-mise.fish" = "/home/me/.config/fish/conf.d/02-loader-mise.fish"
"config/fish/conf.d/02-loader-oh-my-posh.fish" = "/home/me/.config/fish/conf.d/02-loader-oh-my-posh.fish"
"config/fish/conf.d/02-loader-op.fish" = "/home/me/.config/fish/conf.d/02-loader-op.fish"
"config/fish/conf.d/02-loader-proto.fish" = "/home/me/.config/fish/conf.d/02-loader-proto.fish"
"config/fish/conf.d/02-loader-starship.fish" = "/home/me/.config/fish/conf.d/02-loader-starship.fish"
"config/fish/conf.d/02-loader-zoxide.fish" = "/home/me/.config/fish/conf.d/02-loader-zoxide.fish"
"config/fish/conf.d/03-alias-aws.fish" = "/home/me/.config/fish/conf.d/03-alias-aws.fish"
"config/fish/conf.d/03-alias-base.fish" = "/home/me/.config/fish/conf.d/03-alias-base.fish"
"config/fish/conf.d/03-alias-docker.fish" = "/home/me/.config/fish/conf.d/03-alias-docker.fish"
"config/fish/conf.d/03-alias-git.fish" = "/home/me/.config/fish/conf.d/03-alias-git.fish"
"config/fish/conf.d/03-alias-melvi.fish" = "/home/me/.config/fish/conf.d/03-alias-melvi.fish"
"config/fish/conf.d/eza.fish" = "/home/me/.config/fish/conf.d/eza.fish"
"config/fish/conf.d/nix.fish" = "/home/me/.config/fish/conf.d/nix.fish"
"config/fish/conf.d/rustup.fish" = "/home/me/.config/fish/conf.d/rustup.fish"
"config/fish/config.fish" = "/home/me/.config/fish/config.fish"
"config/ghostty/command.sh" = "/home/me/.config/ghostty/command.sh"
"config/ghostty/config" = "/home/me/.config/ghostty/config"
"config/nvim/init.lua" = "/home/me/.config/nvim/init.lua"
"config/nvim/lazy-lock.json" = "/home/me/.config/nvim/lazy-lock.json"
"config/nvim/lua/config/lazy.lua" = "/home/me/.config/nvim/lua/config/lazy.lua"
"config/nvim/lua/config/remap.lua" = "/home/me/.config/nvim/lua/config/remap.lua"
"config/nvim/lua/config/set.lua" = "/home/me/.config/nvim/lua/config/set.lua"
"config/nvim/lua/plugins/copilot.lua" = "/home/me/.config/nvim/lua/plugins/copilot.lua"
"config/nvim/lua/plugins/fugitive.lua" = "/home/me/.config/nvim/lua/plugins/fugitive.lua"
"config/nvim/lua/plugins/harpoon.lua" = "/home/me/.config/nvim/lua/plugins/harpoon.lua"
"config/nvim/lua/plugins/leap.lua" = "/home/me/.config/nvim/lua/plugins/leap.lua"
"config/nvim/lua/plugins/lsp.lua" = "/home/me/.config/nvim/lua/plugins/lsp.lua"
"config/nvim/lua/plugins/lualine.lua" = "/home/me/.config/nvim/lua/plugins/lualine.lua"
"config/nvim/lua/plugins/nvim-terminal.lua" = "/home/me/.config/nvim/lua/plugins/nvim-terminal.lua"
"config/nvim/lua/plugins/rose-pine.lua" = "/home/me/.config/nvim/lua/plugins/rose-pine.lua"
"config/nvim/lua/plugins/telescope.lua" = "/home/me/.config/nvim/lua/plugins/telescope.lua"
"config/nvim/lua/plugins/tidy.lua" = "/home/me/.config/nvim/lua/plugins/tidy.lua"
"config/nvim/lua/plugins/treesitter.lua" = "/home/me/.config/nvim/lua/plugins/treesitter.lua"
"config/nvim/lua/plugins/undotree.lua" = "/home/me/.config/nvim/lua/plugins/undotree.lua"
"config/nvim/lua/plugins/vim-repeat.lua" = "/home/me/.config/nvim/lua/plugins/vim-repeat.lua"
"config/nvim/lua/plugins/vim-surround.lua" = "/home/me/.config/nvim/lua/plugins/vim-surround.lua"
"config/nvim/lua/plugins/vim-tmux-navigator.lua" = "/home/me/.config/nvim/lua/plugins/vim-tmux-navigator.lua"
"config/starship.toml" = "/home/me/.config/starship.toml"
"config/tmux/tmux.conf" = "/home/me/.config/tmux/tmux.conf"

[templates]
