[helpers]

[settings]
default_target_type = "automatic"

[nvim.files]
"config/nvim" = "~/.config/nvim/"

[fish.files]
"config/fish" = "~/.config/fish/" 

[nushell.files]
"config/nushell" = "~/.config/nushell"

[tmux.files]
"config/tmux" = "~/.config/tmux"

[ghostty.files]
"config/ghostty" = "~/.config/ghostty"

[wallpapers.files]
wallpapers = "~/Pictures/wallpapers/"
