[helpers]

[settings]
default_target_type = "automatic"

[nvim.files]
"config/nvim" = "~/.config/nvim/"

[fish.files]
"config/fish" = "~/.config/fish/" 

[nushell.files]
"config/nushell" = "~/.config/nushell"

[tmux.files]
"config/tmux" = "~/.config/tmux"

[ghostty.files]
"config/ghostty" = "~/.config/ghostty"

[oh-my-posh.files]
"config/oh-my-posh" = { target =  "~/.config/oh-my-posh", type = "symbolic" }

[starship.files]
"config/starship.toml" = "~/.config/starship.toml"

[wallpapers.files]
wallpapers = "~/Pictures/wallpapers/"

[git.files]
"config/git" = "~/.config/git/"
